const Products =[
    {
        id: 4,
        name: "Watch",
        image: 'https://m.media-amazon.com/images/I/71kbRVr8YfL._AC_SX679_.jpg',
        image1:"https://m.media-amazon.com/images/I/61s7t-m5IwL._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/71-pQ833lAL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/61Oagprax-L._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/810NUvErb8L._AC_SX679_.jpg",
        brand: "Fossil Men's Sports Watch",
        tagline: "Fossil Men's Sports Watch with Stainless Steel, Silicone, or Leather Band",
        rating: "3",
        price: "10491",
        about: "Purposeful design details define our time-honored watch collection, Fossil Blue Dive."
      },
    {
        id:5,
        name:"TV",
        image:'https://m.media-amazon.com/images/I/815E5aShTqL._AC_SL1500_.jpg',
        image1:"https://m.media-amazon.com/images/I/71I0EKE1YRL._AC_SL1500_.jpg",
        image2:"https://m.media-amazon.com/images/I/71QVvTKgZML._AC_SL1500_.jpg",
        image3:"https://m.media-amazon.com/images/I/71hsgwxqEzL._AC_SL1500_.jpg",
        image4:"https://m.media-amazon.com/images/I/71I0EKE1YRL._AC_SX679_.jpg",
        brand:"Realme Smart Tv",
        tagline:"INSIGNIA 32-inch Class F20 Series Smart HD 720p Fire TV with Alexa Voice Remote (NS-32F201NA23)",
        rating: "4",
        price:"9599",
        about :" 720p resolution View your favorite movies,shows and games in high definition.Alexa voice control - The Alexa Voice Remote lets you easily control your entertainment, search across apps, switch inputs, and more using just your voice. Press and hold the voice button and ask Alexa to easily find, launch, and control content, and even switch to cable.Fire TV experience built-in - Watch over 1 Million streaming movies and TV episodes with access to tens of thousands of channels, apps, and Alexa skills."
    },
    {
        id:6,
        name:"SAMSUNG Galaxy A35",
        image:'https://m.media-amazon.com/images/I/71YwZXmVcEL._AC_SL1500_.jpg',
        image1:"https://m.media-amazon.com/images/I/71Fq2slLXAL._AC_SL1500_.jpg",
        image2:"https://m.media-amazon.com/images/I/710jNG37iyL._AC_SL1500_.jpg",
        image3:"https://m.media-amazon.com/images/I/71eBwwf5Y+L._AC_SL1500_.jpg",
        image4:"https://m.media-amazon.com/images/I/61ot9yExQzL._AC_SL1500_.jpg",
        brand:"SAMSUNG",
        tagline:"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone",
        rating: "4",
        price:"27479",
        about :"CIRCLE IT, SEARCH IT, FIND IT. JUST LIKE THAT: What’s your favorite influencer wearing? Where’d they go on vacation? What’s that word mean? Don’t try to describe it — use Circle to Search with Google¹ and get the answer in a snapOUR BRIGHTEST GALAXY A SERIES SCREEN YET: Thanks to Vision Booster, the screen seamlessly adjusts to your surroundings so you can enjoy uninterrupted streaming, gaming or browsing² even on the sunniest afternoon STUNNING SHOTS. VIVID VIDEO: Advanced triple-lens camera of turns every moment into a masterpiece; With high-res photos & high-definition video, it’s easy to capture awe-worthy content and optical image stabilization lets you capture it blur-free"
    },    
    {
        id:7,
        name:"BENGOO G9000",
        image:'https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SL1000_.jpg',
        image1:"https://m.media-amazon.com/images/I/71z2WmHMtZL._AC_SL1000_.jpg",
        image2:"https://m.media-amazon.com/images/I/71Ie8vokMuL._AC_SL1000_.jpg",
        image3:"https://m.media-amazon.com/images/I/71rxKLsCxqL._AC_SL1000_.jpg",
        image4:"https://m.media-amazon.com/images/I/71732pdsbQL._AC_SL1000_.jpg",
        brand:"BENGOO ",
        tagline:"BENGOO G9000 Stereo Gaming Headset for PS4 PC Xbox One PS5 Controller",
        rating: "4",
        price:"1571",
        about:"【Multi-Platform Compatible】Support PlayStation 4, New Xbox One, PC, Nintendo 3DS, Laptop, PSP, Tablet, iPad, Computer, Mobile Phone. Please note you need an extra Microsoft Adapter (Not Included) when connect with an old version Xbox One controller. 【Surrounding Stereo Subwoofer】Clear sound operating strong brass, splendid ambient noise isolation and high precision 40mm magnetic neodymium driver, acoustic positioning precision enhance the sensitivity of the speaker unit, bringing you vivid sound field, sound clarity, shock feeling sound. Perfect for various games like Halo 5 Guardians, Metal Gear Solid, Call of Duty, Star Wars Battlefront, Overwatch, World of Warcraft Legion, etc."
    },  
    {
        id:8,
        name:"Handle Bag",
        image:'https://m.media-amazon.com/images/I/614ZmQXU09L._AC_SY575_.jpg',
        image1:"https://m.media-amazon.com/images/I/61Uim1PJhCL._AC_SY575_.jpg",
        image2:"https://m.media-amazon.com/images/I/316HYEtjQTL._AC_US40_.jpg",
        image3:"https://m.media-amazon.com/images/I/515AjwJodAL._AC_SY575_.jpg",
        image4:"https://m.media-amazon.com/images/I/61-RQ5rWouL._AC_SX575_.jpg",
        brand:"Michael Kors",
        tagline:"The Drop Women's Addison Soft Volume Top-Handle Bag",
        rating: "4",
        price:"9414",
        about:"Authentic Michael Kors, dust bag NOT included3 compartments, center zip compartment"
    }, 
    {
        id:9,
        name:"Rice Cooker",
        image:'https://m.media-amazon.com/images/I/61K3C51cf1L._AC_SX679_.jpg',
        image1:"https://m.media-amazon.com/images/I/61eT4TyjehL._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/61D5OHhHOiL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/71z0Q+tPNWL._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/71UbH4ZfgqL._AC_SX679_.jpg",
        brand:"CUCKOO",
        tagline:"CUCKOO Basic Rice Cooker & Warmer with Nonstick Inner Pot, Rice Cooker 6-Cup Uncooked",
        rating: "4",
        price:"3386.",
        about:"Easy-to-Use Functionality: With a simple switch press, indulge in delicious and flawlessly cooked rice, and seamlessly transition to keep-warm mode post-cooking Mid to Large Capacity: The 6-cup (12 cups cooked) rice cooker provides the perfect serving amount for small gatherings or small to medium sized families"
    }, 
    {
        id:10,
        name:"Water Filter",
        image:'https://m.media-amazon.com/images/I/71Ad21j1dkL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        image1:"https://m.media-amazon.com/images/I/81vgY4Uue2L._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/81E2HuVV8OL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/81A4OauuCVL._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/71YFnjpEuiL._AC_SX679_.jpg",
        brand:"Brita",
        tagline:"Brita Hub Instant Powerful Countertop Water Filter System educes 70+ Contaminants, 12 Cup Water Reservoir",
        rating: "4",
        price:"8998.",
        about:"BRITA'S BEST FILTER EVER: This unique instant water filtration device provides Brita's best water filtration ever. The Brita Hub filter reduces 70+ contaminants including lead, chlorine, microplastics and more. GREAT TASTE, LESS WASTE: Get great tasting water without the waste. By switching to this Brita water filter dispenser, your family can save money and replace around 1800 single-use plastic water bottles a yea"
    }, 
    {
        id:11,
        name:"iPhone case",
        image:'https://m.media-amazon.com/images/I/51i2i4QxOLL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        image1:"https://m.media-amazon.com/images/I/51ljFrV3qsL._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/512Wb46eKZL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/51hISlpUT2L._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/51JFqsW-0hL._AC_SX679_.jpg",
        brand:"CASETiFY",
        tagline:"CASETiFY Ultra Impact iPhone 11 Pro Max Case [9.8ft Drop Protection] - Check II - Baby Blue Twist - Clear",
        rating: "4",
        price:"2088",
        about:"Compatible with iPhone 11 Pro Max Only (6.5 Screen Size) Made from CASETiFY's innovative, shock-resistant qìtech material, this iPhone case comes equipped with an impact-absorbing inner layer, protecting phones from up to 9.8ft drops."
    }, 
    {
        id:12,
        name:"Face Wash",
        image:'https://m.media-amazon.com/images/I/71BIj7NOS0L._SX425_.jpg',
        image1:"https://m.media-amazon.com/images/I/81TUPdONdtL._SX425_.jpg",
        image2:"https://m.media-amazon.com/images/I/71PEUSuHebL._SX425_.jpg",
        image3:"https://m.media-amazon.com/images/I/71vPWTu9vOL._SX425_.jpg",
        image4:"https://m.media-amazon.com/images/I/71342CJKQ-L._SX425_.jpg",
        brand:"Srripo",
        tagline:"Gentle Foaming Face Wash, Deep Cleansing Facial Cleanser with Brush Moisturizing & Non-Irritating Face Cleanser ",
        rating: "5",
        price:"5077",
        about:"Gentle Foaming Face Wash, Deep Cleansing Facial Cleanser with Brush Moisturizing & Non-Irritating Face Cleanser for Sensitive Dry All Skin, PH Balancing Oil Control Pore Cleaner for Fresh(Blue)"
    }, 
    {
        id:13,
        name:"Face Clear",
        image:'https://m.media-amazon.com/images/I/714IGF8ZqnL._AC_SL1500_.jpg',
        image1:"https://m.media-amazon.com/images/I/91m7MPAkPXL._AC_SL1500_.jpg",
        image2:"https://m.media-amazon.com/images/I/81KOQqfPCAL._AC_SL1500_.jpg",
        image3:"https://m.media-amazon.com/images/I/71ujIcOenfL._AC_SL1500_.jpg",
        image4:"https://m.media-amazon.com/images/I/91gi1hp9J2L._AC_SL1500_.jpg",
        brand:"Clean & Clear",
        tagline:"Clean & Clear 2-Pack Oil-Free Facial Cleansers with Citrus Scent, Morning Burst and Night Relaxing, 16 oz",
        rating: "4",
        price:"634",
        about:"Daily Facial Cleanser Morning and Night Set: One 8 fl oz bottle of Clean & Clear Day and one 8 fl oz bottle of Clean & Clear Night Face Wash; both oil-free and non-comedogenic to gently cleanse without over-drying skin both in the morning and at night"
    }, 
    {
        id:14,
        name:"Blends",
        image:'https://m.media-amazon.com/images/I/71yqZM6BZ8L._AC_SX679_.jpg',
        image1:"https://m.media-amazon.com/images/I/710fjcV+CLL._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/71gVojwy6QL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/81jU+sACbWL._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/81WpndG4J7L._AC_SX679_.jpg",
        brand:"Vitamix",
        tagline:"Vitamix Propel 510 Propel Blender with Pre-set Blending Programs, Professional-Grade, 48-oz Capacity, Black",
        rating: "4",
        price:"23710",
        about:"The Propel 510 with its 48oz container is ideal for everything from individual servings to full size blends. 3 Pre-set Programs: Smoothie, Hot Soup, and Frozen Dessert program settings ensure ideal, consistent blending results with walk-away convenience."
    }, 
    {
        id:15,
        name:"Samsung Galaxy Tab",
        image:'https://m.media-amazon.com/images/I/71-hJGtkLWL._AC_SX425_.jpg',
        image1:"https://m.media-amazon.com/images/I/71ppS4KkKEL._AC_SX425_.jpg",
        image2:"https://m.media-amazon.com/images/I/81+2YBNrs8L._AC_SX425_.jpg",
        image3:"https://m.media-amazon.com/images/I/7108UI4dK8L._AC_SX425_.jpg",
        image4:"https://m.media-amazon.com/images/I/61Sc+8acg3L._AC_SX425_.jpg",
        brand:"SAMSUNG",
        tagline:"Samsung Galaxy Tab S6 Lite 10.4' 64GB WiFi Android Tablet, S Pen Included, Gaming Ready, ",
        rating: "4",
        price:"16938.",
        about:"GALAXY TAB S6 LITE, MORE POWERFUL THAN EVER: With an included S Pen, crystal-clear display and Dolby Atmos surround sound, this reliable tablet is all about fun plus a little work CHANGE THE WAY YOU NOTE: It’s easier than ever to write notes, edit photos and videos, mark up documents and more with the included S Pen"
    }, 
    {
        id:16,
        name:"Bed Pillows",
        image:'https://m.media-amazon.com/images/I/71329CVoVDL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        image1:"https://m.media-amazon.com/images/I/81I2-8l8aNL._AC_SX679_.jpg",
        image2:"https://m.media-amazon.com/images/I/71b9xVdukEL._AC_SX679_.jpg",
        image3:"https://m.media-amazon.com/images/I/81R+-E+MELL._AC_SX679_.jpg",
        image4:"https://m.media-amazon.com/images/I/81R+-E+MELL._AC_SX679_.jpg",
        brand:"Beckham Hotel Collection",
        tagline:"Beckham Hotel Collection Bed Pillows Standard / Queen Size Set of 2 - Down Alternative Bedding Gel Cooling Pillow",
        rating: "4",
        price:"978",
        about:"Cotton UPERIOR COMFORT - Queen pillows have a 250 thread count Cotton Cover filled with a soft 100% Polyester Fill. One of the best first apartment or new home essentials gift for bedroom, guest bed room, college dorm or house decor."
    }, 
    {
        id:17,
        name:"dumbbell ",
        image:'https://m.media-amazon.com/images/I/61jau6tusOL._AC_SX569_.jpg',
        image1:"https://m.media-amazon.com/images/I/617ynRzdwlL._AC_SX569_.jpg",
        image2:"https://m.media-amazon.com/images/I/71AojasVrNL._AC_SX569_.jpg",
        image3:"https://m.media-amazon.com/images/I/71NZj7D1qWL._AC_SX569_.jpg",
        image4:"https://m.media-amazon.com/images/I/71QjAVPTAXL._AC_SX569_.jpg",
        brand:"Bowflex",
        tagline:"Bowflex SelectTech 552 Adjustable Dumbbells ",
        rating: "4",
        price:"32099",
        about:" WIDER WEIGHT RANGE: Each dumbbell adjust from 5 to 52.5 lb. in 2.5 lb. increments up to 25 lb. TURN OF A DIAL: Select the weight you want with the turn of the dial – no more picking up 15 different dumbbells to give you the results you want.",
    },
    {
        id:18,
        name:"Strength Training Bench",
        image:'https://m.media-amazon.com/images/I/71LLGB4onjL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        image1:"https://m.media-amazon.com/images/I/81+3TSeG7FL._AC_SX569_.jpg",
        image2:"https://m.media-amazon.com/images/I/819Vrx7LGYL._AC_SX569_.jpg",
        image3:"https://m.media-amazon.com/images/I/81L8YkrchUL._AC_SX569_.jpg",
        image4:"https://m.media-amazon.com/images/I/81cIbLFVGQL._AC_SX569_.jpg",
        brand:"	FLYBIRD",
        tagline:"FLYBIRD Weight Bench, Adjustable Strength Training Bench for Full Body Workout with Fast Folding-New Version",
        rating: "4",
        price:"9484",
        about:"【FLYBIRD】Design and produce fitness equipment for 20 years. Especially in WEIGHT BENCH, the bench was designed with advice of professional coach. You need a durable bench, Not a one month bench. 【2021 High Quality Bench】Made of commercial thickness steel, past thousands of weight test to ensure safety for workout everytime, Not the mendacious bench.",
    },
    
    
   

]
export default Products;